CREATE DATABASE IF NOT EXISTS base;

use base;

CREATE TABLE IF NOT EXISTS members (
    id INT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(255) NULL,
    surname VARCHAR(255) NULL,
    country VARCHAR(255) NULL,
    email VARCHAR(255) NULL,
    password VARCHAR(255) NOT NULL,
    online BOOLEAN
);

CREATE TABLE IF NOT EXISTS messages (
    id INT(255) NOT NULL AUTO_INCREMENT PRIMARY KEY, 
    name VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL,
    time DATE NOT NULL
);
